### ISSUE TITLE
Issues running yarn start dev

### ISSUE THREAD

**Issue by jaysnel** [MeshJS/mesh#154]
Hello, I am trying to get the storybook up and running to view the components inside fo the `/react` folder but get the following error when running the `dev` command. Are there any special environment variables that I would need?

```
ℹ ｢wdm｣: wait until bundle finished: 
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/X/Desktop/projects/mesh/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/X/Desktop/projects/mesh/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/X/Desktop/projects/mesh/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/X/Desktop/projects/mesh/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/X/Desktop/projects/mesh/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/X/Desktop/projects/mesh/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/X/Desktop/projects/mesh/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/X/Desktop/projects/mesh/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by jaysnel** [comment]
Solution: Use node V16
